# Site Info
title: Jeremiah Flaga
title2:  Jeremiah Flaga
tagline: My thoughts and experiences on programming, life, atbp.
description: 'My thoughts and experiences on programming, life, atbp.'
author: Jeremiah Flaga
baseurl: ""
url:
logo: '/images/jboy-papyrus-blue.png'
email: flaga.jeremiah@gmail.com
background: /images/background/small/arif-riyanto-vJP-wZ6hGBg-unsplash.jpg

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple # https://prashanthchengi.livejournal.com/80490.html | https://jekyllfieldguide.com/tutorials/jekyll-dual-language/
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # GitHub-flavored Emoji plugin for Jekyll

markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Pagination
paginate: 10
paginate_path: '/blog/page:num'
permalink: /:year/:month/:day/:title/

paginate_multiple:
  - paginate: 2
    paginate_path: '/reviews/page:num/'
    sub_dir: '/reviews'

timezone: UTC

# Social Profiles
twitter_username:   jboyflaga
github_username:    jeremiahflaga
facebook_username:  jboyflaga
instagram_username:  
linkedin_username:  jeremiahflaga

google_analytics:   UA-93514486-1 # out your google-analytics code
disqus_short_name: 'jeremiahflaga' # leave blank if you don't want disqus


# Exclude these files from your production _site
exclude:
  - README.md
  - resume/sections
  - resume/anti-resume/sections
  - resume/2021/sections
  - resume/2021/anti-resume/sections
